"""empty message

Revision ID: c17650a89261
Revises: dda8f2e84674
Create Date: 2019-04-23 18:06:19.829883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17650a89261'
down_revision = 'dda8f2e84674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'wish_id')
    )
    op.add_column('wishes', sa.Column('granted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'granted_by')
    op.drop_table('likes')
    # ### end Alembic commands ###
