"""empty message

Revision ID: dda8f2e84674
Revises: ec9a3054dc68
Create Date: 2019-04-23 17:52:09.873490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda8f2e84674'
down_revision = 'ec9a3054dc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('granted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'granted_at')
    # ### end Alembic commands ###
