"""empty message

Revision ID: ec9a3054dc68
Revises: f18c9bef7fb5
Create Date: 2019-04-23 17:37:20.823446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9a3054dc68'
down_revision = 'f18c9bef7fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishes', sa.Column('granted', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'granted')
    # ### end Alembic commands ###
